export interface LiveChannel {
  id: string;
  name: string;
  group: '央视' | 'CGTN' | '卫视' | '国际' | '其他';
  category: string;
  url: string;
  source: string;
  website?: string;
}

export const liveChannels: LiveChannel[] = [
  {
    id: 'cctv-4-europe',
    name: 'CCTV-4 Europe',
    group: '央视',
    category: '综合',
    url: 'https://dash2.antik.sk/live/test_cctv_tizen/playlist.m3u8',
    source: 'iptv-org',
    website: 'http://tv.cctv.com/cctv4europe/',
  },
  {
    id: 'cctv-9',
    name: 'CCTV-9 纪录',
    group: '央视',
    category: '纪录',
    url: 'https://xykt-fix.github.io/Y77.m3u8',
    source: 'iptv-org',
    website: 'http://tv.cctv.com/cctv9/',
  },
  {
    id: 'cctv-10',
    name: 'CCTV-10 科教',
    group: '央视',
    category: '科教',
    url: 'https://cdn4.skygo.mn/live/disk1/CCTV-10/HLSv3-FTA/CCTV-10.m3u8',
    source: 'iptv-org',
    website: 'http://tv.cctv.com/cctv10/',
  },
  {
    id: 'cctv-11',
    name: 'CCTV-11 戏曲',
    group: '央视',
    category: '戏曲',
    url: 'https://xykt-fix.github.io/play/a02b/index.m3u8',
    source: 'iptv-org',
    website: 'http://tv.cctv.com/cctv11/',
  },
  {
    id: 'cctv-15',
    name: 'CCTV-15 音乐',
    group: '央视',
    category: '音乐',
    url: 'https://xykt-fix.github.io/play/a02e/index.m3u8',
    source: 'iptv-org',
    website: 'http://tv.cctv.com/cctv15/',
  },
  {
    id: 'cctv-plus-1',
    name: 'CCTV+ 1',
    group: '央视',
    category: '新闻',
    url: 'https://cd-live-stream.news.cctvplus.com/live/smil:CHANNEL1.smil/playlist.m3u8',
    source: 'CCTV+',
    website: 'https://www.cctvplus.com/',
  },
  {
    id: 'cctv-plus-2',
    name: 'CCTV+ 2',
    group: '央视',
    category: '新闻',
    url: 'https://cd-live-stream.news.cctvplus.com/live/smil:CHANNEL2.smil/playlist.m3u8',
    source: 'CCTV+',
    website: 'https://www.cctvplus.com/',
  },
  {
    id: 'cgtn',
    name: 'CGTN',
    group: 'CGTN',
    category: '新闻',
    url: 'https://english-livebkali.cgtn.com/live/encgtn.m3u8',
    source: 'CGTN',
    website: 'https://www.cgtn.com/tv',
  },
  {
    id: 'cgtn-news',
    name: 'CGTN News',
    group: 'CGTN',
    category: '新闻',
    url: 'https://news.cgtn.com/resource/live/english/cgtn-news.m3u8',
    source: 'CGTN',
    website: 'https://www.cgtn.com/tv',
  },
  {
    id: 'cgtn-documentary',
    name: 'CGTN Documentary',
    group: 'CGTN',
    category: '纪录',
    url: 'https://english-livebkali.cgtn.com/live/doccgtn.m3u8',
    source: 'CGTN',
    website: 'https://www.cgtn.com/channel/documentary',
  },
  {
    id: 'cgtn-global-biz',
    name: 'CGTN Global Biz',
    group: 'CGTN',
    category: '财经',
    url: 'https://amg01314-amg01314c6-distrotv-us-10220.playouts.now.amagi.tv/playlist/amg01314-cgtn-cgtnglobalbiz-distrotvus/playlist.m3u8',
    source: 'iptv-org',
  },
  {
    id: 'cgtn-arabic',
    name: 'CGTN Arabic',
    group: '国际',
    category: '新闻',
    url: 'https://news.cgtn.com/resource/live/arabic/cgtn-a.m3u8',
    source: 'CGTN',
    website: 'https://arabic.cgtn.com/',
  },
  {
    id: 'cgtn-french',
    name: 'CGTN French',
    group: '国际',
    category: '新闻',
    url: 'https://news.cgtn.com/resource/live/french/cgtn-f.m3u8',
    source: 'CGTN',
    website: 'https://francais.cgtn.com/',
  },
  {
    id: 'cgtn-russian',
    name: 'CGTN Russian',
    group: '国际',
    category: '新闻',
    url: 'https://news.cgtn.com/resource/live/russian/cgtn-r.m3u8',
    source: 'CGTN',
    website: 'https://russian.cgtn.com/',
  },
  {
    id: 'cgtn-spanish',
    name: 'CGTN Spanish',
    group: '国际',
    category: '新闻',
    url: 'https://news.cgtn.com/resource/live/espanol/cgtn-e.m3u8',
    source: 'CGTN',
    website: 'https://espanol.cgtn.com/',
  },
  {
    id: 'china-travel',
    name: 'China Travel',
    group: '国际',
    category: '文旅',
    url: 'https://amg01314-amg01314c7-distrotv-us-10219.playouts.now.amagi.tv/playlist/amg01314-cgtn-cgtnchinatravel-distrotvus/playlist.m3u8',
    source: 'iptv-org',
  },
  {
    id: 'discovering-china',
    name: 'Discovering China',
    group: '国际',
    category: '纪录',
    url: 'https://amg01314-amg01314c8-distrotv-us-10218.playouts.now.amagi.tv/playlist/amg01314-cgtn-cgtndiscoveringchina-distrotvus/playlist.m3u8',
    source: 'iptv-org',
  },
  {
    id: 'dragon-tv-international',
    name: '东方卫视国际',
    group: '卫视',
    category: '综合',
    url: 'https://op-group1-swiftservesd-1.dens.tv/s/s29/index.m3u8',
    source: 'iptv-org',
  },
  {
    id: 'shenzhen-satellite-tv',
    name: '深圳卫视',
    group: '卫视',
    category: '综合',
    url: 'https://livepull-tcms.sztv.com.cn/live/sz4Kpgm.m3u8',
    source: '深圳广电',
  },
  {
    id: 'zhejiang-satellite-tv',
    name: '浙江卫视',
    group: '卫视',
    category: '综合',
    url: 'https://play-qukan.cztv.com/live/1758879019692345.m3u8',
    source: '浙江广电',
  },
  {
    id: 'zhejiang-international',
    name: '浙江国际',
    group: '卫视',
    category: '综合',
    url: 'https://ali-m-l.cztv.com/channels/lantian/channel10/1080p.m3u8',
    source: '浙江广电',
  },
];
